apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
    - nodePort: 0
      port: 80
      targetPort: 80
      protocol: TCP
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker-registry.default.svc:5000/knative-serving/helloworld
            env:
              - name: TARGET
                value: "Chris Bartling and Roland Rutkowski at HealthPartners"